wallpaper {
    monitor = eDP-1
    path = /home/dip/.config/hypr/chainsaw-man.jpg
    fit_mode = cover
}
    splash = false

wallpaper {
    monitor = HDMI-A-2
    path = /home/dip/.config/hypr/chainsaw-man.jpg
    fit_mode = cover
}
    splash = false
